DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comment;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  bio TEXT NOT NULL,
  following TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
    slug TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    body TEXT NOT NULL,
    tagList TEXT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    favorited TEXT NOT NULL,
    favoritesCount INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    PRIMARY KEY (slug),
    FOREIGN KEY (author_id) REFERENCES user (id)

);

CREATE TRIGGER update_Timestamp
    AFTER UPDATE 
    ON post
BEGIN
   UPDATE post SET updatedAt = CURRENT_TIMESTAMP WHERE slug=OLD.slug;
END;

CREATE TABLE comment (
    article_id TEXT NOT NULL,
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body TEXT NOT NULL,
    author_id INTEGER NOT NULL,
    FOREIGN KEY (article_id) REFERENCES post (slug)
);